# Remplacez VOTRE-PSEUDO par votre pseudo GitHub, puis :
#   kubectl apply -f argocd/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jabdoulie/taskflow-gitops.git
    targetRevision: main
    path: apps/taskflow
  destination:
    server: https://kubernetes.default.svc
    namespace: taskflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
